sudo: false
# Trusty (14.04) distribution supports TLS 1.2. Whereas the default distribution (Precise 12.04) for Travis does not.
# More details https://github.com/travis-ci/travis-ci/issues/7131#issuecomment-273239428
dist: trusty
env:
  global:
    TERRAFORM_VERSION: "0.8.2"

install:
- mkdir bin
- curl -o ./bin/terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
- unzip -d ./bin ./bin/terraform.zip
- chmod +x ./bin/terraform

script:
- ./bin/terraform validate terraform
