%% Sequence Diagram for dns deployment
sequenceDiagram
  participant Github
  participant CI
  participant Concourse
  participant AWS

  note over Github: dns repo
  loop Github dns repo change request
    Github ->>+ CI: Opened pull request

    Note over CI: Runs terraform validation tests
    Note over CI: Merges pull request on success
    CI -->>- Github: Delete pull request branch
  end

  Note over Github: cg-pipeline-tasks repo
  Note over Github: dns repo
  Github ->> Concourse: Deploys updated deploy branch

  Note over Concourse: terraform apply
  Concourse ->> AWS: update dns, save terraform state

  Note over Concourse: Report dns nameserver information
